#ReadMe
- read: false
#Updates and Corrections
- read: false
#Bilateral Assistance, MAIN DATA
- read: false
#Country Summary (€)
- read: true
  extract:
    name: "Country Summary (€)" # Name of the sheet. This is case and empty string sensitive
    column_range: "B:AI" # Range specifies which part of the sheet to extract
    number_rows: 43 # In this case: 51 (last row) - 8 (begin of table) = 43
    skip_rows: 7
    number_header_rows: 2
  transform:
    clean_column_names: true
  load:
    name: "a_summary_€"
#Country Summary ($)
- read: true
  extract:
    name: "Country Summary ($)" # Name of the sheet. This is case and empty string sensitive
    column_range: "B:AI" # Range specifies which part of the sheet to extract
    number_rows: 43 # In this case: 51 (last row) - 8 (begin of table) = 43
    skip_rows: 7
    number_header_rows: 2
  transform:
    clean_column_names: true
  load:
    name: "b_summary_$"
#Aggregates by Country Group
- read: false
#Fig 1. Allocated over time
- read: true
  extract:
    name: "Fig 1. Allocated over time" # Name of the sheet. This is case and empty string sensitive
    column_range: "B:L" # Range specifies which part of the sheet to extract
    number_rows: 33 #40-7 = 33
    skip_rows: 6
    number_header_rows: 1
  transform:
    clean_column_names: true
    columnnames:
      Finanicial aid, allocated (€ billion), without US: "Financial aid, allocated (€ billion), without US"
    datetime:
      Month: "%b-%Y"
  load:
    name: "c_allocated_over_time"
#Fig 2. Country Groups (stacked)
- read: false # can be done by querying a_summary_€ or b_summary_$ with a group by statement
#Fig 3. Ranking (€)
- read: false # can be done by querying e_allocations_refugees_€ without refugee cost estimation
#Fig 4. Ranking, %
- read: false # Can be done by excluding refugee cost estimations of f_bilateral_allocations_gdp_pct
#Fig 5. Rank. Alloc vs Comm (€)
- read: true
  extract:
    name: "Fig 5. Rank. Alloc vs Comm (€)"
    column_range: "B:D" # Country, Committed aid, Allocated aid
    number_rows: 39 # From US to Malta, excluding total
    skip_rows: 10 # Skip title, description, and blank rows to reach header
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "d_allocations_vs_commitments"
#Fig 6. With Refugee Support, €"
- read: true
  extract:
    name: "Fig 6. With Refugee Support, €"
    column_range: "B:F"
    number_rows: 42
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
    add_columns: # Move this under transform
      gdp_2021:
        source_table: "a_summary_€"
        join_query: |
          SELECT 
            r.*, 
            s.gdp_2021__billion as gdp_2021
          FROM temp_transform_table r
          LEFT JOIN "a_summary_€" s 
          ON r.country = s.country
  load:
    name: "e_allocations_refugees_€"
#Fig 7. With Refugee Support, %"
- read: true
  extract:
    name: "Fig 7. With Refugee Support, %"
    column_range: "B:D" # Just three columns: Country and Total, Refugess Cost Estimates
    number_rows: 37 # From Denmark to China, excluding total
    skip_rows: 10 # Skip title, description, and blank rows to reach header
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "f_bilateral_allocations_gdp_pct"
#Fig 8. Military Aid
- read: false # can be done by querying "e_allocations_refugees_€"
#Fig 9. Heavy Weapon Ranking"
- read: true
  extract:
    name: "Fig 9. Heavy Weapon Ranking"
    column_range: "B:C" # Just two columns: Country and Total
    number_rows: 37 # From Denmark to China, excluding total
    skip_rows: 10 # Skip title, description, and blank rows to reach header
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "g_heavy_weapon_ranking"
#Fig 10. Financial Aid by type"
- read: true
  extract:
    name: "Fig 10. Financial Aid by type"
    column_range: "B:F" # Country, Loan, Grant, Guarantee, Central bank swap line
    number_rows: 43 # From EU Institutions to Malta
    skip_rows: 10 # Skip title, description, and blank rows to reach header
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "h_financial_aid_by_type"
#Fig 11. Budget Support by Donor"
- read: true
  extract:
    name: "Fig 11. Budget Support by Donor"
    column_range: "B:D" # Country, Allocations (loans, grants, and guarantees), Disbursements
    number_rows: 24 # From EU Institutions to Taiwan
    skip_rows: 10 # Skip title, description, and blank rows to reach header
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "i_budget_support_by_donor"
#Fig 12. Weapon Stocks UKR RU / We will need two reading instructions here to handle both tables individually
- read: true
  extract:
    name: "Fig 12. Weapon Stocks UKR RU"
    column_range: "B:F"
    number_rows: 6
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
    reshape:
      type: "melt"
      id_vars: ["item"] # Now matches cleaned column name
      value_vars: ["howitzer155mm", "mlrs", "tanks", "ifvs"] # Now matches cleaned column names
      var_name: "equipment_type"
      value_name: "quantity"
  load:
    name: "j_weapon_stocks_base"
- read: true
  extract:
    name: "Fig 12. Weapon Stocks UKR RU"
    column_range: "B:F" # Item, Type, Ukraine Need, Delivered, To be Delivered, Ukrainian stock
    number_rows: 3 # The three weapon type rows
    skip_rows: 19 # Skip to the second table
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "k_weapon_stocks_detail"
#Fig 13. NATO Stocks"
- read: true #TODO: This is not working rn
  extract:
    name: "Fig 13. NATO Stocks"
    column_range: "B:R" # From Country through Total % Committed
    number_rows: 5 # Three weapon types (TANKS, HOWITZERS, MLRS) plus country codes
    skip_rows: 11 # Skip title, description, blank rows to reach the first data row
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "l_nato_weapon_stocks"
#Fig 14. Share of stocks pledged"
- read: true
  extract:
    name: "Fig 14. Share of stocks pledged"
    column_range: "B:N" # From Country through all weapon system share columns
    number_rows: 34 # From Norway through Romania
    skip_rows: 10 # Skip title, description to reach the header
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "m_share_of_stocks_pledged"
# Fig 15. Comparison WW2 (weap.)"
- read: true
  extract:
    name: "Fig 15. Comparison WW2 (weap.)"
    column_range: "B:E"
    number_rows: 22
    skip_rows: 9
    number_header_rows: 1
  transform:
    clean_column_names: true
    replace_values:
      To be delivered:
        .: 0
    datatypes:
      To be delivered: int
    forward_fill_column: "Military conflict"
  load:
    name: "n_comparison_spain_ww2_equipment"
# Fig 16. Comparison WW2 % GDP"
- read: true
  extract:
    name: "Fig 16. Comparison WW2 % GDP"
    column_range: "B:D"
    number_rows: 7
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "o_comparison_ww2_gdp"
# Fig 16. Comparison WW2 % GDP"
- read: true
  extract:
    name: "Fig 16. Comparison WW2 % GDP"
    column_range: "F:H"
    number_rows: 7
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "p_comparison_ww2_abs"
#Fig 17. Comp. with US wars"
- read: true
  extract:
    name: "Fig 17. Comp. with US wars"
    column_range: "B:D"
    number_rows: 6
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "q_comparison_us_wars_gdp"
    #Fig 17. Comp. with US wars"
- read: true
  extract:
    name: "Fig 17. Comp. with US wars"
    column_range: "G:I"
    number_rows: 6
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "r_comparison_us_wars_abs"
#Fig 18. Comparison Gulf War"
- read: true
  extract:
    name: "Fig 18. Comparison Gulf War"
    column_range: "B:D"
    number_rows: 5
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "s_comparison_gulf_war_gdp"
#Fig 18. Comparison Gulf War"
- read: true
  extract:
    name: "Fig 18. Comparison Gulf War"
    column_range: "G:I"
    number_rows: 5
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "t_comparison_gulf_war_abs"
#Fig 19. Comp. European Crises"
- read: true
  extract:
    name: "Fig 19. Comp. European Crises"
    column_range: "B:C"
    number_rows: 4
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "u_comparison_european_crises"
#Fig 20. Domestic Priorities"
- read: true
  extract:
    name: "Fig 20. Domestic Priorities"
    column_range: "B:D"
    number_rows: 8
    skip_rows: 11
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "v_comparison_domestic_abs"
#Fig 20. Domestic Priorities"
- read: true
  extract:
    name: "Fig 20. Domestic Priorities"
    column_range: "J:L"
    number_rows: 8
    skip_rows: 11
    number_header_rows: 1
  transform:
    clean_column_names: true
  load:
    name: "w_comparison_domestic_gdp"
#Fig 21. Priorities Germany"
- read: true
  extract:
    name: "Fig 21. Priorities Germany"
    column_range: "B:F"
    number_rows: 6
    skip_rows: 10
    number_header_rows: 1
  transform:
    clean_column_names: true
    replace_values:
      Total bilateral aid:
        .: 0
      EU aid shares:
        .: 0
      Cost:
        .: 0
    datatypes:
      Total bilateral aid: float
      EU aid shares: float
      Cost: float
    entry_correction: true
  load:
    name: "x_comparison_germany_abs"
#Fig A1. Transparency Index"
- read: false
#Fig A2. Ranking % GDP + EU"
- read: false
#Fig A3. Units over Time"
- read: false
#Fig A4. Weapon Delivery"
- read: false
#Fig A5. Tank Unit Ranking"
- read: false
#Fig A6. East vs West Deliver"
- read: false
#Fig A7. Delivery Transparency"
- read: false
#Fig A8. Comm over Time"
- read: false
#Fig A9. Cumu Heavy per Month"
- read: false
#Fig A10. Mult. year over time"
- read: false
#Fig A11. US Mil Alloc over time"
- read: false
#Fig A12. EU Fin Alloc over time"
- read: false
#Fig A13. EU vs US Comm & Alloc"
- read: false
#Fig A14. Alloc Mil Eur vs US"
- read: false
#Fig A15. Alloc Tot Eur vs US"
- read: false
#Fig A16. Alloc top donors"
- read: false
#Fig A17. Ranking (€ bn.+ EU)"
- read: false
#Fig A18. Ranking (€) (comm)"
- read: false
#Fig A19. Refugee Number"
- read: false
#Fig A20. Budget supp. over time"
- read: false
#Fig A21. Eur vs US Weapon Alloc"
- read: false
#Fig A22. Aid composition"
- read: false
#Fig A23. Patriot-like stock
- read: false
# Fig A24 Scenario Analysis
- read: false
# Fig A25 Cumulative Alloc.
- read: false
# Comm. by type and month
- read: false
# Allocations by type and month
- read: false
# Commitments per Month
- read: false
# Comm. per Month Military
- read: false
# Allocations per Month
- read: false
# Alloc. per Month (Heavy Weap)
- read: false
# Allocations per Month Military
- read: false
# Financial disb per Month (€)
- read: false
# Delivery Transparency Index
- read: false
# Designated Websites, total sums
- read: false
# Data Transparency Index
- read: false
# Country_Deflator
- read: false
# BEA_Deflator
- read: false
# EIB Aid Shares
- read: false
# EU Aid Shares
- read: false
# Exchange Rates (time series)
- read: false
# Inflation
- read: false
# Exchange Rates (current)
- read: false
# Heavy Weapon Stocks
- read: false
# Historical comparison (data)
- read: false
# In-kind Military per Country
- read: false
# International Initiatives
- read: false
# Price List, Weapons & Items
- read: false
# Refugees Recorded
- read: false
# Refugee Cost Calculations
- read: false
# Share, Heavy Weapons to Ukraine
- read: false
# Summary of US acts
- read: false
# Table Aid vs Energy
- read: false
# Table European Crisis
- read: false
# Table Gulf War
- read: false
