[tool.ruff]
# Added PD (flake8-pydantic) to the selected rules
select = ["E", "F", "W", "I", "N", "D", "UP", "B", "C4", "PD"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.8
target-version = "py38"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
# Ignore imported but unused in __init__.py files
"__init__.py" = ["F401"]
# Ignore specific rules in tests
"tests/*" = ["D100", "D101", "D102", "D103", "D104"]

[tool.ruff.isort]
known-first-party = []
known-third-party = ["pydantic"]  # Added pydantic to third-party imports
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.pydantic]
# Warn about missing `frozen` parameter in pydantic models
warn-required-frozen = true
# Warn about missing `frozen` parameter in dataclasses
warn-required-dataclass-frozen = true
# Maximum number of allowed fields in a model
max-model-attributes = 25
# Warn if a model has no fields
warn-empty-model = true
